### ISSUE TITLE
Catch error when Puppeteer is not able to initialize chrome

### ISSUE THREAD

**Issue by GauthierPLM** [JoshTheDerf/prerenderer#42]
When using prerender-spa-plugin with Puppeteer renderer on zeit.co, Chrome is not able to properly initialize itself because of a missing system dependency. When it happens, an Promise rejection is send but the Puppeteer renderer fails to catch it, which leads the build not to properly terminal and fail.

I am not sure if the error should be catch by the renderer or by the plugin, so I post this issue here.

This can be easily reproduced by creating a project with prerender-spa-plugin and Puppeteer renderer and deploying it on zeit.co, either via git or via their [`now` CLI](https://zeit.co/download).

```
Downloading 126 deployment files...
Installing build runtime...
Build runtime installed: 422.668ms
Looking up build cache...
Build cache found [30.53 MB, 27650 files]
Build cache unpacked: 1431.986ms
Installing dependencies...
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > sass-loader@8.0.0" has unmet peer dependency "webpack@^4.36.0".
warning " > style-resources-loader@1.3.2" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
Done in 21.02s.
Running "yarn run build"
yarn run v1.17.3
$ vue-cli-service build

-  Building for production...
Starting type checking service...
Using 1 worker with 2048MB memory limit
Error: Failed to launch chrome!
/zeit/7433591d/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/zeit/7433591d/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/zeit/7433591d/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
(node:544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at PuppeteerRenderer.destroy (/zeit/7433591d/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:140:21)
    at Prerenderer.destroy (/zeit/7433591d/node_modules/@prerenderer/prerenderer/es6/index.js:87:20)
    at PrerendererInstance.initialize.then.then.then.then.then.then.then.then.catch.err (/zeit/7433591d/node_modules/prerender-spa-plugin/es6/index.js:144:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Tofandel** [comment]
This has been fixed, all errors are properly handled now during the `prerender.initialize()` promise, you can use `try catch` in an async function or `.catch()`
